PTHREAD = shared
OPTION =
#OPTION += -DCHECK_INDEX_VALIDATION
#OPTION += -DCHECK_MALLOC_FREE
#OPTION += -DCHECK_VARCHAR_EXTLEN
#OPTION += -DDO_NOT_CHECK_DISKFREESPACE
#OPTION += -DDO_NOT_FSYNC
#OPTION += -DDO_NOT_SUPPORT_MDB_SYSLOG
#OPTION += -DDO_NOT_USE_ERROR_DESC
#OPTION += -DDO_NOT_USE_MDB_DEBUGLOG
#OPTION += -DHIDDEN__DECL_PREFIX
#OPTION += -DINDEX_BUFFERING
#OPTION += -DSEGMENT_NO_65536
#OPTION += -D_64BIT

ENABLE_YACC = 0
JNI = 0
# interactive prompt 
HAVE_READLINE=0

COMPILER = clang
COMPILE_MODE = mode64
